name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: self-hosted
 
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup npm cache directory
      run: |
        mkdir -p $RUNNER_TEMP/npm-cache
        npm config set cache $RUNNER_TEMP/npm-cache
    - name: Install dependencies
      run: npm ci
    - name: Setup environment
      run: |
        touch .env 
        echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env
        chmod 600 .env  
        ls -lah .env 
    - name: Restart application
      run: pm2 restart server.js
